// app/(other)/layout.tsx
import { NotificationProvider } from '@/context/useNotificationContext' // adjust path if needed

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function OtherLayout({ children }: { children: React.ReactNode }) {
  return (
    <div className="other-layout">
      <NotificationProvider>{children}</NotificationProvider>
    </div>
  )
}
